### PR TITLE
Make the IOData wrapper work for most cases.

### PR DESCRIPTION
**Pull request by tovrstra**
## Steps

- [x] Write a good description of what the PR does.
- [x] Add tests for each unit of code added (e.g. function, class)
- [x] Update documentation
- [x] Squash commits that can be grouped together
- [x] Rebase onto master

## Description

- Add a return value to from_iodata, the make sure the caller gets a complete description of the basis set.
- Removed hard-coded conventions for spherical functions, no longer needed.
- Set all normalization constants for the contractions to 1.0. IOData does not impose this convention.
- Just use some convention for Cartesian functions when this info is not provided by IOData. Which is used does not matter.
- Remove redundant arguments from _replace call.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

## Related Issue

This fixes a part of #78.

### CODE REVIEW

**Comment by tovrstra** [comment]
The tests fail only because of previously existing formatting issues, which are fixed in #105.

**Comment by tovrstra** [comment]
I'll rerun the tests after merging the fixes for black. They should pass now, if not I'll fix.

**Comment by evohringer** [comment]
Toon, we are experiencing some problems with basis sets containing f functions in molden file format (more specifically the def2-TZVP basis set from ORCA).
The error is 
```
File "charges_param/gbasis/wrappers.py", line 114, in angmom_components_sph
    "Only the real solid harmonics as defined in Helgaker Section 6.4.2. is "
NotImplementedError: Only the real solid harmonics as defined in Helgaker Section 6.4.2. is supported.
```

 Do you think these changes will fix it?

**Comment by wilhadams** [comment]
@evohringer these changes won't fix the issue, it has to do with the way `gbasis` deals with ordering the pure (spherical) functions, which doesn't yet support ORCA-style conventions. This will be fixed soon.

**Review by wilhadams — APPROVED** [review]

**Pull request merged**
