### PR TITLE
Basis Sets Tutorial Notebook

### PR DESCRIPTION
**Pull request by maximilianvz**
## Steps

- [X] Write a good description of what the PR does.
- [ ] ~Add tests for each unit of code added (e.g. function, class)~
- [ ] ~Update documentation~
- [X] Squash commits that can be grouped together
- [ ] Rebase onto master

## Description

This is a separated notebook corresponding to the *Basis Sets* section of the notebook from PR #142 (closed).

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |
| ✓  | :hammer: Refactoring  |
| ✓  | :scroll: Docs |

### CODE REVIEW

**Comment by marco-2023** [comment]
Hi @maximilianvz  @FarnazH  I don't have a way to push commits to this PR. I am pushing some changes to https://github.com/marco-2023/gbasis/tree/basis_set_tutorial. Max, when I am finished you can pull them to your local branch and then push them to this PR. I think the examples are great but need to show more gbasis features. I am planning to finish polishing this Notebook and we can use it as a sort of template for the others.

**Comment by leila-pujal** [comment]
hi @marco-2023, I think you should be able to push changes to Max's PR. I think you have to add Max's repo and fetch his branch (I use this https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes).  Let me know if you need help trying it.

**Comment by marco-2023** [comment]
Hi @maximilianvz @FarnazH I made a new PR #158 (it is the finished version of this one but was rebased on the master branch). I thought it would be better than a force push here. I think it may be better if we continue making the necessary revisions there. I will continue going through the evaluations tutorial.

**Comment by maximilianvz** [comment]
@FarnazH and @marco-2023, if we can agree to move ahead with PR #158, we should close this PR. @marco-2023, do you think you'll have to take this approach (rebasing and then making a new PR) for the other two notebooks as well?

**Comment by marco-2023** [comment]
Hi @maximilianvz for the other notebooks we need the changes that were made to the API merged in the branches in which we are making the notebooks. The options I see for doing this are:
  1. merge `master` into each of the notebook branches
  2. rebase the notebook branches into `master` and force-push the branches
  3. rebase the notebook branches into `master` and push them as new branches/PRs

I am in favor of either 2 or 3 (the approach seems cleaner), 3 is the more conservative approach. If you could 2 on the other two notebook branches it would be perfect.

**Comment by maximilianvz** [comment]
@marco-2023, I just finished doing the second approach you suggested on the other 2 notebooks. If you still wish to go with the third option, I'll leave that up to your discretion.

**Comment by marco-2023** [comment]
Perfect @maximilianvz, I will add my updates to the current branches then. Thank you very much.

**Comment by FarnazH** [comment]
See #158.

**Comment by FarnazH** [comment]
See #158.

**Pull request closed without merging**
